export const MODIFIERS: Record<string, string> = {
  ALT: "Alt",
  CTRL: "Control",
  CONTROL: "Control",
  SHIFT: "Shift",
  META: "Meta",
  COMMAND: "Meta",
  WIN: "Meta",
};

export const PLAYWRIGHT_KEYS: Record<string, string> = {
  ALT: "Alt",
  ARROWDOWN: "ArrowDown",
  ARROWLEFT: "ArrowLeft",
  ARROWRIGHT: "ArrowRight",
  ARROWUP: "ArrowUp",
  UP: "ArrowUp",
  DOWN: "ArrowDown",
  LEFT: "ArrowLeft",
  RIGHT: "ArrowRight",
  BACKSPACE: "Backspace",
  CAPSLOCK: "CapsLock",
  CMD: "Meta",
  COMMAND: "Meta",
  CTRL: "Control",
  CONTROL: "Control",
  DELETE: "Delete",
  END: "End",
  ENTER: "Enter",
  ESC: "Escape",
  HOME: "Home",
  INSERT: "Insert",
  OPTION: "Alt",
  PAGEDOWN: "PageDown",
  PAGEUP: "PageUp",
  SHIFT: "Shift",
  SPACE: " ",
  SUPER: "Meta",
  TAB: "Tab",
};
